import "./globals.css"
import { ReactNode } from "react"

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="es">
      <body className="min-h-screen bg-white text-black">{children}</body>
    </html>
  )
}

//add favvicons
